"""empty message

Revision ID: 3ea4b8b7fa8e
Revises: ff7c387a6728
Create Date: 2024-01-12 17:21:40.900205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea4b8b7fa8e'
down_revision = 'ff7c387a6728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
