"""empty message

Revision ID: 8f66ad6586d7
Revises: 3ea4b8b7fa8e
Create Date: 2024-01-27 11:04:42.141231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f66ad6586d7'
down_revision = '3ea4b8b7fa8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doc_table')
    op.drop_table('doc')
    op.drop_table('doc_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_text',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('doc_text_id', sa.INTEGER(), nullable=False),
    sa.Column('doc_text_data', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_text_id')
    )
    op.create_table('doc',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('vendor', sa.VARCHAR(length=80), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=80), nullable=False),
    sa.Column('doc_link', sa.VARCHAR(length=80), nullable=False),
    sa.Column('doc_table_id', sa.INTEGER(), nullable=False),
    sa.Column('doc_text_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_link'),
    sa.UniqueConstraint('doc_table_id'),
    sa.UniqueConstraint('doc_text_id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('vendor')
    )
    op.create_table('doc_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('doc_table_id', sa.INTEGER(), nullable=False),
    sa.Column('doc_table_data', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_table_id')
    )
    # ### end Alembic commands ###
