"""empty message

Revision ID: ff7c387a6728
Revises: ec164c6bda96
Create Date: 2023-12-27 15:35:57.462236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7c387a6728'
down_revision = 'ec164c6bda96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
